//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.CompanyCommunicator.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.CompanyCommunicator.Common.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacte seu adminstrador de TI para lhe conceder acesso..
        /// </summary>
        public static string AdminConsentError {
            get {
                return ResourceManager.GetString("AdminConsentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicativo não instalado..
        /// </summary>
        public static string AppNotInstalled {
            get {
                return ResourceManager.GetString("AppNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status da Entrega.
        /// </summary>
        public static string ColumnName_DeliveryStatus {
            get {
                return ResourceManager.GetString("ColumnName_DeliveryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportado por.
        /// </summary>
        public static string ColumnName_ExportedBy {
            get {
                return ResourceManager.GetString("ColumnName_ExportedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo de Exportação.
        /// </summary>
        public static string ColumnName_ExportTimeStamp {
            get {
                return ResourceManager.GetString("ColumnName_ExportTimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título da Mensagem.
        /// </summary>
        public static string ColumnName_MessageTitle {
            get {
                return ResourceManager.GetString("ColumnName_MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo de Envio.
        /// </summary>
        public static string ColumnName_SentTimeStamp {
            get {
                return ResourceManager.GetString("ColumnName_SentTimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status da Reação.
        /// </summary>
        public static string ColumnName_StatusReason {
            get {
                return ResourceManager.GetString("ColumnName_StatusReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID da Equipe.
        /// </summary>
        public static string ColumnName_TeamId {
            get {
                return ResourceManager.GetString("ColumnName_TeamId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da Equipe.
        /// </summary>
        public static string ColumnName_TeamName {
            get {
                return ResourceManager.GetString("ColumnName_TeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPN.
        /// </summary>
        public static string ColumnName_Upn {
            get {
                return ResourceManager.GetString("ColumnName_Upn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID do Usuário.
        /// </summary>
        public static string ColumnName_UserId {
            get {
                return ResourceManager.GetString("ColumnName_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string ColumnName_UserName {
            get {
                return ResourceManager.GetString("ColumnName_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (cópia).
        /// </summary>
        public static string DuplicateText {
            get {
                return ResourceManager.GetString("DuplicateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algo deu errado. Tente exportar os resultados novamente..
        /// </summary>
        public static string ExportFailureText {
            get {
                return ResourceManager.GetString("ExportFailureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha em criar a conversa. Mensagem de erro: {0}.
        /// </summary>
        public static string FailedToCreateConversationFormat {
            get {
                return ResourceManager.GetString("FailedToCreateConversationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha em criar a conversar para o usuário: {0}. Exceção: {1}.
        /// </summary>
        public static string FailedToCreateConversationForUserFormat {
            get {
                return ResourceManager.GetString("FailedToCreateConversationForUserFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha na criação da conversa. Falha na Requisição. Mensagem de Erro: {0}&quot;.
        /// </summary>
        public static string FailedToCreateConversationThrottledFormt {
            get {
                return ResourceManager.GetString("FailedToCreateConversationThrottledFormt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha na procura da Equipe {0} na Base de Dados..
        /// </summary>
        public static string FailedToFindTeamInDbFormat {
            get {
                return ResourceManager.GetString("FailedToFindTeamInDbFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha na sincronização de todos os usuários. Código do Status: {0}, Exceção: {1}.
        /// </summary>
        public static string FailedToGetAllUsersFormat {
            get {
                return ResourceManager.GetString("FailedToGetAllUsersFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha na busca do id da conversa para o usuário: {0}. Código do Status: {1} Exceção: {2}.
        /// </summary>
        public static string FailedToGetConversationForUserFormat {
            get {
                return ResourceManager.GetString("FailedToGetConversationForUserFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha na busca dos membros do grupo {0}: {1}.
        /// </summary>
        public static string FailedToGetMembersForGroupFormat {
            get {
                return ResourceManager.GetString("FailedToGetMembersForGroupFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha na busca dos membros da Equipe {0}: {1}.
        /// </summary>
        public static string FailedToGetMembersForTeamFormat {
            get {
                return ResourceManager.GetString("FailedToGetMembersForTeamFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha na instalação do aplicativo para o usuário: {0}. Exceção: {1}.
        /// </summary>
        public static string FailedToInstallApplicationForUserFormat {
            get {
                return ResourceManager.GetString("FailedToInstallApplicationForUserFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha na preparação da mensagem para envio: {0}.
        /// </summary>
        public static string FailtoPrepareMessageFormat {
            get {
                return ResourceManager.GetString("FailtoPrepareMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O arquivo contém os resultados da exportação..
        /// </summary>
        public static string FileCardDescription {
            get {
                return ResourceManager.GetString("FileCardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O link para download expirou. Esporte novamente os resultados..
        /// </summary>
        public static string FileCardExpireText {
            get {
                return ResourceManager.GetString("FileCardExpireText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportData.
        /// </summary>
        public static string FileName_ExportData {
            get {
                return ResourceManager.GetString("FileName_ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_Delivery.
        /// </summary>
        public static string FileName_Message_Delivery {
            get {
                return ResourceManager.GetString("FileName_Message_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        public static string FileName_Metadata {
            get {
                return ResourceManager.GetString("FileName_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu arquivo está pronto para download. A cópia está disponível no OneDrive..
        /// </summary>
        public static string FileReadyText {
            get {
                return ResourceManager.GetString("FileReadyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algo deu errado. Tente exportar os resultados novamente..
        /// </summary>
        public static string FileUploadErrorText {
            get {
                return ResourceManager.GetString("FileUploadErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A notificação tem {0} grupos como destinatários. Não deve exceder {1} grupos..
        /// </summary>
        public static string NumberOfGroupsExceededLimitWarningFormat {
            get {
                return ResourceManager.GetString("NumberOfGroupsExceededLimitWarningFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A notificação tem {0} listas como destinatários. Não deve exceder {1} listas..
        /// </summary>
        public static string NumberOfRostersExceededLimitWarningFormat {
            get {
                return ResourceManager.GetString("NumberOfRostersExceededLimitWarningFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A notificação tem {0} equipes como destinatários. Não deve exceder {1} equipes..
        /// </summary>
        public static string NumberOfTeamsExceededLimitWarningFormat {
            get {
                return ResourceManager.GetString("NumberOfTeamsExceededLimitWarningFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissão recusada. Não prosseguiremos com a exportação..
        /// </summary>
        public static string PermissionDeclinedText {
            get {
                return ResourceManager.GetString("PermissionDeclinedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinatário não encontrado.
        /// </summary>
        public static string RecipientNotFound {
            get {
                return ResourceManager.GetString("RecipientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucesso..
        /// </summary>
        public static string Succeeded {
            get {
                return ResourceManager.GetString("Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha..
        /// </summary>
        public static string Throttled {
            get {
                return ResourceManager.GetString("Throttled", resourceCulture);
            }
        }
    }
}
